# Generated by Django 3.0 on 2019-12-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeBrowFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_name', models.CharField(max_length=200)),
                ('eyebrow_face', models.ImageField(upload_to='')),
            ],
        ),
    ]
